name: Mercury Health Core CI/CD

on: [push]

jobs:
  # publish IaC as build artifact
  uploadIaC:
    runs-on: windows-latest

    steps:
    # checkout code from repo
    - name: checkout repo
      uses: actions/checkout@v1

    # upload IaC folder
    - name: upload IaC
      uses: actions/upload-artifact@master
      with:
        name: IaC
        path: IaC

# provision infrastructure in Azure
  provisionInfra:
    needs: uploadIaC
    runs-on: windows-latest
    steps:
    # download IaC artifact
    - name: download IaC
      uses: actions/download-artifact@master
      with:
        name: IaC

    - name: look for ps1 file
      run: |
        Get-ChildItem '${{ github.workspace }}'

    - name: provision webapp and db infrastructure in azure
      env:
        SERVICE_PRINCIPAL: http://62e58f3b-cc53-468e-9e7b-7c9198dfd273/automagically-demo-spn
        SERVICE_PRINCIPAL_TENANT: 62e58f3b-cc53-468e-9e7b-7c9198dfd273
        AZURE_SUBSCRIPTION_NAME: "Microsoft Azure Sponsorship"
        RESOURCE_GROUP: MercuryHealthCore
        RESOURCE_GROUP_REGION: eastus
        SERVER_NAME: maxtestmercuryhealthcoredbserverbeta
        DB_LOCATION: eastus
        ADMIN_LOGIN: maxtest
        START_IP: 0.0.0.0
        END_IP: 0.0.0.0
        DB_NAME: maxtestmercuryhealthcoredbbeta
        WEB_APP_NAME: maxtestmercuryhealthcore-beta
        ENVIRONMENT: "[beta]"
      run: >
        powershell -command "& '${{ github.workspace }}\IaC\AzCLI\provisionWebAndDB.ps1'" 
        -servicePrincipal %SERVICE_PRINCIPAL% 
        -servicePrincipalSecret ${{ secrets.SERVICE_PRINCIPAL_SECRET }} 
        -servicePrincipalTenantId %SERVICE_PRINCIPAL_TENANT% 
        -azureSubscriptionName %AZURE_SUBSCRIPTION_NAME% 
        -resourceGroupName %RESOURCE_GROUP% 
        -resourceGroupNameRegion %RESOURCE_GROUP_REGION% 
        -serverName %SERVER_NAME% 
        -dbLocation %DB_LOCATION% 
        -adminLogin %ADMIN_LOGIN% 
        -adminPassword ${{ secrets.DB_PASSWORD }} 
        -startip %START_IP% 
        -endip %END_IP% 
        -dbName %DB_NAME% 
        -webAppName %WEB_APP_NAME% 
        -environment %ENVIRONMENT%
